DECLARE @ VARROUTE
SELECT
@VARROUTE = ROUTE
FROM S1217815.MIGRATION
WHERE MIGRATION_ID = PYTHON VAR
SELECT SDO_GEOM.SDO_INTERSECTION(VARROUTE,
(SELECT ROUTE FROM S1217815.MIGRATION),.005) FROM S1217815.MIGRATION;


DECLARE @N TABLE(
C int,
D SDO_GEOMETRY)
INSERT INTO @N (C, D)
SELECT MIGRATION_ID, ROUTE
FROM S1217815.MIGRATION
WHERE MIGRATION_ID = PYTHONVARIABLE
SELECT A.MIGRATION_ID, A.NAME
FROM S1217815.MIGRATION A, @N B
WHERE SDO_RELATE(A.ROUTE, B.D, 'MASK = OVERLAPBDYDISJOINT') = 'TRUE'
AND A.MIGRATION_ID = VARIABLE;


DEF ROUTE2 = PYTHONVVV
SELECT A.MIGRATION_ID, A.NAME,
SDO_GEOM.RELATE(A.ROUTE, &ROUTE2, 'MASK = OVERLAPBDYDISJOINT') = 'TRUE'
FROM S1217815.MIGRATION A
WHERE A.MIGRATION_ID = VARIABLE;
UNDEFINE ROUTE2

SELECT SDO_GEOM.SDO_INTERSECTION(A.ROUTE,B.SHAPE/AREA,.005)
FROM S1217815.MIGRATION A, S1217815.REGION B
WHERE A.MIGRATION_ID = VAR1 AND B.REGION_ID = VAR2;

SELECT A.MIGRATION_ID, A.NAME, B.REGION_ID, B.NAME
FROM S1217815.MIGRATION A, S1217815.REGION B
WHERE SDO_RELATE(A.ROUTE, B.LOCATION, 'MASK = OVERLAPBDYDISJOINT') = 'TRUE'
AND A.MIGRATION_ID = VAR1 AND B.REGION_ID = VAR2;

SELECT SDO_GEOM.SDO_DISTANCE(A.LOCATION, B.LOCATION, .005)
FROM S1217815.SETTLEMENTS A, S1217815.FOODSOURCE B
WHERE A.SETTLEMENT_ID = VAR1 AND B.SOURCE_ID = VAR2;

DEF HAB1 = PV
DEF HAB2 = PVV
SELECT SDO_GEOM.SDO_DISTANCE(&HAB1, &HAB2, .005) FROM S1217815.REGION;
UNDEFINE HAB1
UNDEFINE HAB2

SELECT A.REGION_ID, A.NAME, B.SETTLEMENT_ID, B.NAME
FROM S1217815.REGION A, S1217815.SETTLEMENTS B
WHERE SDO_CONTAINS(A.AREA, B.LOCATION) = 'TRUE';

SELECT A.REGION_ID, A.NAME, B.SOURCE_ID
FROM S1217815.REGION A, S1217815.FOOD_SOURCE B
WHERE SDO_CONTAINS(A.AREA, B.LOCATION) = 'TRUE';
