--POINT IN POLYGON

--Settlement in Region
SELECT A.REGION_ID, A.NAME, B.SETTLEMENT_ID, B.NAME
FROM S1234874.REGION A, S1234874.SETTLEMENTS B
WHERE SDO_CONTAINS(A.SHAPE, B.LOCATION) = 'TRUE'
AND B.SETTLEMENT_ID = VARC;

--Food source in region
SELECT A.REGION_ID, A.NAME, B.SOURCE_ID
FROM S1234874.REGION A, S1234874.FOOD_SOURCE B
WHERE SDO_CONTAINS(A.SHAPE, B.LOCATION) = 'TRUE'
AND B.SOURCE_ID = VARE;

--user in region
SELECT A.REGION_ID, A.NAME
FROM S1234874.REGION A
WHERE SDO_CONTAINS(A.SHAPE,
SDO_GEOMETRY(2001, 8307, SDO_POINT_TYPE(-133,62, NULL), NULL, NULL)) = 'TRUE';


--INTERSECTION

--migration route intersect
SELECT A.MIGRATION_ID, B.MIGRATION_ID
FROM S1234874.MIGRATION A, S1234874.MIGRATION B
WHERE A.MIGRATION_ID = 4
AND SDO_RELATE(A.ROUTE, B.ROUTE, 'MASK = TOUCH') = 'TRUE';

--region intersect (ish do they interact, can change mask)
SELECT A.NAME, B.NAME
FROM S1234874.REGION A, S1234874.REGION B
WHERE A.REGION_ID = PYVAR
AND SDO_RELATE(A.SHAPE, B.SHAPE, 'MASK = ANYINTERACT') = 'TRUE';

--region and route intersect
SELECT A.NAME, B.MIGRATION_ID
FROM S1234874.REGION A, S1234874.MIGRATION B
WHERE A.REGION_ID = PYVAR
AND SDO_RELATE(A.SHAPE, B.ROUTE, 'MASK = ANYINTERACT') = 'TRUE';
--option?
SELECT A.NAME, B.MIGRATION_ID
FROM S1234874.REGION A, S1234874.MIGRATION B
WHERE A.MIGRATION_ID = PYVAR
AND SDO_GEOM.SDO_INTERSECTION(A.SHAPE, B.ROUTE, 0) = 'TRUE';


--DISTANCE

-- distance between regions (currently returns zero though)
SELECT A.NAME, B.NAME, SDO_GEOM.SDO_DISTANCE(A.SHAPE, B.SHAPE, .005)
FROM S1234874.REGION A, S1234874.REGION B
WHERE A.REGION_ID = 8 AND B.REGION_ID = 7;

--distance between settlement and route
SELECT A.NAME, B.MIGRATION_ID, SDO_GEOM.SDO_DISTANCE(A.LOCATION, B.ROUTE, .005)
FROM S1234874.SETTLEMENTS A, S1234874.MIGRATION B
WHERE A.SETTLEMENT_ID = 10 AND B.MIGRATION_ID = 3;

--distance between settlement and food source (untested)
SELECT A.NAME, B.SOURCE_ID, SDO_GEOM.SDO_DISTANCE(A.LOCATION, B.LOCATION, .005)
FROM S1234874.SETTLEMENTS A, S1234874.FOOD_SOURCE B
WHERE A.SETTLEMENT_ID = 10 AND B.SOURCE_ID = 3;
