DROP TABLE SETTLEMENTS;

CREATE TABLE SETTLEMENTS
(SETTLEMENT_ID NUMBER(2),
NAME VARCHAR2(25),
LOCATION MDSYS.SDO_GEOMETRY,
PRIMARY KEY (SETTLEMENT_ID, NAME));

GRANT SELECT,UPDATE,INSERT,DELETE ON SETTLEMENTS TO s1217815,s1676540;
