LOAD DATA
INFILE 
dragontypeid.csv
REPLACE
INTO TABLE 
s1217815.DRAGON_TYPE
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(TYPE_ID, DIET_ID, WINGSPAN_ID, COLOUR_ID, FIRE, NOTES)