LOAD DATA
INFILE 
dragontypes.csv
REPLACE
INTO TABLE 
s1217815.DRAGONS
FIELDS TERMINATED BY ',' OPTIONALLY ENCLOSED BY '"'
TRAILING NULLCOLS
(DRAGON_ID, NAME, REGION_WINTER_ID, REGION_SUMMER_ID, TYPE_ID)