SET FEEDBACK OFF
SET UNDERLINE =
SET PAGESIZE 500
SET LINESIZE 80
SET RECSEP WRAPPED
SET RECSEPCHAR "-"
BREAK ON "Settlement ID" SKIP 1

TTITLE LEFT "Settlements table"
COLUMN "Settlement ID" FORMAT 99
COLUMN "Name" FORMAT a15
COLUMN "Location" FORMAT a35


SELECT SETTLEMENT_ID "Settlement ID", NAME "Name", LOCATION "Location"
FROM s1234874.SETTLEMENTS
ORDER BY SETTLEMENT_ID
/
SET RECSEP OFF
CLEAR COLUMNS
CLEAR BREAKS
TTITLE OFF
