SET FEEDBACK OFF
SET UNDERLINE =
SET PAGESIZE 500
SET LINESIZE 100
SET RECSEP WRAPPED
SET RECSEPCHAR "-"
BREAK ON "Region ID" SKIP 1

TTITLE LEFT "Regions table"
COLUMN "Region ID" FORMAT 99
COLUMN "Name" FORMAT a15
COLUMN "Season" FORMAT a10
COLUMN "Temp Min (C)" FORMAT 99
COLUMN "Temp Max (C)" FORMAT 99
COLUMN "Shape" FORMAT a25 WOR

SELECT REGION_ID "Region ID", NAME "Name", SEASON "Season", TEMP_MIN "Temp Min (C)", TEMP_MAX "Temp Max (C)", SHAPE "Shape"
FROM s1234874.REGION
ORDER BY REGION_ID
/
SET RECSEP OFF
CLEAR COLUMNS
CLEAR BREAKS
TTITLE OFF
