SET FEEDBACK OFF
SET UNDERLINE =
SET PAGESIZE 500
SET LINESIZE 65
SET RECSEP WRAPPED
SET RECSEPCHAR "-"
BREAK ON "Migration ID" SKIP 1

TTITLE LEFT "Migration table"
COLUMN "Migration ID" FORMAT 99
COLUMN "Route" FORMAt a50 WOR


SELECT MIGRATION_ID "Migration ID", ROUTE "Route"
FROM s1234874.MIGRATION
ORDER BY MIGRATION_ID
/
SET RECSEP OFF
CLEAR COLUMNS
CLEAR BREAKS
TTITLE OFF
