DROP INDEX REGION_IDX;
DELETE FROM USER_SDO_GEOM_METADATA;

INSERT INTO USER_SDO_GEOM_METADATA (
    TABLE_NAME, COLUMN_NAME, DIMINFO, SRID
  ) VALUES (
    'REGION',
    'SHAPE',
    SDO_DIM_ARRAY(
      SDO_DIM_ELEMENT('LONG', -180.0, 180.0, 0.5),
      SDO_DIM_ELEMENT('LAT', -90.0, 90.0, 0.5)
    ),
    8307
  );


SELECT * FROM USER_SDO_GEOM_METADATA
WHERE TABLE_NAME = UPPER('REGION')
AND COLUMN_NAME = UPPER('SHAPE');

CREATE INDEX region_idx ON region( shape ) INDEXTYPE IS MDSYS.SPATIAL_INDEX;
