DROP TABLE DRAGONS;

CREATE TABLE DRAGONS
(DRAGON_ID NUMBER(2),
NAME VARCHAR2(25),
REGION_SUMMER_ID NUMBER(2),
REGION_WINTER_ID NUMBER(2),
TYPE_ID NUMBER(2),
MIGRATION_ID NUMBER(2),
PRIMARY KEY (DRAGON_ID,NAME),
FOREIGN KEY (REGION_SUMMER_ID) REFERENCES REGION(REGION_ID),
FOREIGN KEY (REGION_WINTER_ID) REFERENCES REGION(REGION_ID),
FOREIGN KEY (TYPE_ID) REFERENCES DRAGON_TYPE(TYPE_ID),
FOREIGN KEY (MIGRATION_ID) REFERENCES MIGRATION(MIGRATION_ID));

GRANT ALL PRIVILEGES ON DRAGONS to s1234874, s1676540;
