DROP TABLE DRAGONS;

CREATE TABLE DRAGONS
(DRAGON_ID NUMBER(2),
NAME VARCHAR2(25),
REGION_SUMMER_ID NUMBER(2),
REGION_WINTER_ID NUMBER(2),
TYPE_ID NUMBER(2),
PRIMARY KEY (DRAGON_ID,NAME),
FOREIGN KEY (REGION_SUMMER_ID) REFERENCES REGION_SUMMER(REGION_SUMMER_ID),
FOREIGN KEY (REGION_WINTER_ID) REFERENCES REGION_WINTER(REGION_WINTER_ID),
FOREIGN KEY (TYPE_ID) REFERENCES DRAGON_TYPE(TYPE_ID));

grant select,update,insert,delete on DRAGONS to s1234874, s1676540;
