CREATE INDEX MIGRATION_IDX
ON S1217815.MIGRATION(ROUTE)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX REGION_IDX
ON S1217815.REGION(AREA)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX SETTLEMENT_IDX
ON S1217815.SETTLEMENTS(LOCATION)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;

CREATE INDEX FOODSOURCE_IDX
ON S1217815.FOOD_SOURCE(LOCATION)
INDEXTYPE IS MDSYS.SPATIAL_INDEX;
