DROP TABLE REGION_SUMMER;

CREATE TABLE REGION_SUMMER
(REGION_SUMMER_ID NUMBER(2),
NAME VARCHAR2(25),
AREA number(2),
TEMP_MAX NUMBER(4),
TEMP_MIN NUMBER (4),
PRIMARY KEY (REGION_SUMMER_ID, NAME));

grant select,update,insert,delete on region_summer to s1234874, s1676540;
