DROP TABLE REGION_SUMMER;

CREATE TABLE REGION_SUMMER
(REGION_SUMMER_ID NUMBER(2),
NAME VARCHAR2(25),
AREA (GEOGRAPHY),
TEMP_MAX NUMBER(4),
TEMP_MIN NUMBER (4),
PRIMARY KEY (REGION_SUMMER_ID, NAME));
