DROP TABLE REGION;

CREATE TABLE REGION_SUMMER
(REGION__ID NUMBER(2),
NAME VARCHAR2(25),
SEASON VARCHAR2(25),
AREA MDSYS.SDO_GEOMETRY,
TEMP_MAX NUMBER(4),
TEMP_MIN NUMBER (4),
PRIMARY KEY (REGION_SUMMER_ID));

grant select,update,insert,delete on region to s1234874, s1676540;
