DROP TABLE SETTLEMENTS;

CREATE TABLE SETTLEMENTS
(SETTLEMENT_ID NUMBER(2),
NAME VARCHAR2(25),
LAT NUMBER(8),
LON NUMBER(8),
REGION_ID NUMBER(2),
PRIMARY KEY (SETTLEMENT_ID, NAME));
REM FOREIGN KEY (REGION_ID) REFERENCES REGION(REGION_ID)

GRANT SELECT,UPDATE,INSERT,DELETE ON DRAGONS TO s1234874,s1676540;
