DROP TABLE DRAGON_TYPE;

CREATE TABLE DRAGON_TYPE
(TYPE_ID NUMBER(2),
DIET_ID NUMBER(2),
WINGSPAN_ID NUMBER(2),
WEIGHT_ID NUMBER(2),
COLOUR_ID NUMBER(2),
FIRE VARCHAR2(4),
NOTES VARCHAR2(50),
PRIMARY KEY (TYPE_ID),
FOREIGN KEY (DIET_ID) REFERENCES DIET(DIET_ID),
FOREIGN KEY (WINGSPAN_ID) REFERENCES WINGSPAN(WINGSPAN_ID),
FOREIGN KEY (WEIGHT_ID) REFERENCES WEIGHT_CLASS(WEIGHT_ID),
FOREIGN KEY (COLOUR_ID) REFERENCES COLOUR(COLOUR_ID));

GRANT ALL PRIVILEGES ON DRAGON_TYPE to s1234874, s1676540;
